#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

echo "echo '✅ Husky pre-commit 실행됨!'" >> .husky/pre-commit
echo '✅ Husky pre-commit 실행됨!'
echo '✅ Husky pre-commit 실행됨!'
echo '✅ Husky pre-commit 실행됨!'
